apiVersion: v1
kind: Secret
metadata:
    name: git-credentials
stringData:
    # For git-sync v3
    GIT_SYNC_USERNAME: your_git_username
    GIT_SYNC_PASSWORD: your_access_token
    # For git-sync v4
    GITSYNC_USERNAME: your_git_username
    GITSYNC_PASSWORD: your_access_token